import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSessionUser } from "@/utils/getSessionUser";
import { Header } from "@/components/Header";
import { getNotifications } from "@/services/notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userData = await getSessionUser();
  const notificationData: any = await getNotifications(userData?.id!);
  return (
    <html lang="en">
      <body className="">
        <main>
          <Header userData={userData!} notificationData={notificationData} />
          {children}
        </main>
      </body>
    </html>
  );
}
